# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_wizard(object):
    def setupUi(self, add_wizard):
        add_wizard.setObjectName("add_wizard")
        add_wizard.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_wizard.sizePolicy().hasHeightForWidth())
        add_wizard.setSizePolicy(sizePolicy)
        add_wizard.setMinimumSize(QtCore.QSize(640, 480))
        add_wizard.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("omnisync.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add_wizard.setWindowIcon(icon)
        add_wizard.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        add_wizard.setModal(True)
        add_wizard.setOptions(QtWidgets.QWizard.NoBackButtonOnLastPage|QtWidgets.QWizard.NoBackButtonOnStartPage|QtWidgets.QWizard.NoCancelButtonOnLastPage)
        self.selection_page = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selection_page.sizePolicy().hasHeightForWidth())
        self.selection_page.setSizePolicy(sizePolicy)
        self.selection_page.setTitle("")
        self.selection_page.setObjectName("selection_page")
        self.option_list = QtWidgets.QListView(self.selection_page)
        self.option_list.setGeometry(QtCore.QRect(10, 1, 581, 341))
        self.option_list.setViewMode(QtWidgets.QListView.ListMode)
        self.option_list.setUniformItemSizes(True)
        self.option_list.setSelectionRectVisible(False)
        self.option_list.setObjectName("option_list")
        add_wizard.addPage(self.selection_page)
        self.auth_page = QtWidgets.QWizardPage()
        self.auth_page.setTitle("")
        self.auth_page.setObjectName("auth_page")
        self.webView = QtWebKitWidgets.QWebView(self.auth_page)
        self.webView.setGeometry(QtCore.QRect(10, 10, 581, 331))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        add_wizard.addPage(self.auth_page)
        self.sync_page = QtWidgets.QWizardPage()
        self.sync_page.setObjectName("sync_page")
        self.selective_sync_box = QtWidgets.QGroupBox(self.sync_page)
        self.selective_sync_box.setEnabled(False)
        self.selective_sync_box.setGeometry(QtCore.QRect(0, 60, 601, 281))
        self.selective_sync_box.setCheckable(False)
        self.selective_sync_box.setObjectName("selective_sync_box")
        self.account_directory_tree = QtWidgets.QTreeView(self.selective_sync_box)
        self.account_directory_tree.setGeometry(QtCore.QRect(10, 60, 581, 211))
        self.account_directory_tree.setObjectName("account_directory_tree")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.selective_sync_box)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 421, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sync_new_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_new_check.sizePolicy().hasHeightForWidth())
        self.sync_new_check.setSizePolicy(sizePolicy)
        self.sync_new_check.setChecked(True)
        self.sync_new_check.setObjectName("sync_new_check")
        self.horizontalLayout.addWidget(self.sync_new_check)
        self.show_files_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_files_check.sizePolicy().hasHeightForWidth())
        self.show_files_check.setSizePolicy(sizePolicy)
        self.show_files_check.setChecked(True)
        self.show_files_check.setObjectName("show_files_check")
        self.horizontalLayout.addWidget(self.show_files_check)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.sync_page)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 591, 33))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.account_folder_text = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_folder_text.sizePolicy().hasHeightForWidth())
        self.account_folder_text.setSizePolicy(sizePolicy)
        self.account_folder_text.setReadOnly(True)
        self.account_folder_text.setObjectName("account_folder_text")
        self.horizontalLayout_2.addWidget(self.account_folder_text)
        self.account_folder_change_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_folder_change_button.sizePolicy().hasHeightForWidth())
        self.account_folder_change_button.setSizePolicy(sizePolicy)
        self.account_folder_change_button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.account_folder_change_button.setObjectName("account_folder_change_button")
        self.horizontalLayout_2.addWidget(self.account_folder_change_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.selective_sync_check = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selective_sync_check.sizePolicy().hasHeightForWidth())
        self.selective_sync_check.setSizePolicy(sizePolicy)
        self.selective_sync_check.setObjectName("selective_sync_check")
        self.horizontalLayout_2.addWidget(self.selective_sync_check)
        self.horizontalLayout_2.setStretch(3, 1)
        add_wizard.addPage(self.sync_page)
        self.last_page = QtWidgets.QWizardPage()
        self.last_page.setSubTitle("")
        self.last_page.setObjectName("last_page")
        add_wizard.addPage(self.last_page)

        self.retranslateUi(add_wizard)
        QtCore.QMetaObject.connectSlotsByName(add_wizard)

    def retranslateUi(self, add_wizard):
        _translate = QtCore.QCoreApplication.translate
        add_wizard.setWindowTitle(_translate("add_wizard", "OmniSync - Add account"))
        self.selection_page.setSubTitle(_translate("add_wizard", "Which type of account would you like to add?"))
        self.auth_page.setSubTitle(_translate("add_wizard", "Authentication"))
        self.sync_page.setSubTitle(_translate("add_wizard", "Account Settings"))
        self.selective_sync_box.setTitle(_translate("add_wizard", "Se&lective Sync Settings"))
        self.sync_new_check.setText(_translate("add_wizard", "Sync new children of partial folders"))
        self.show_files_check.setText(_translate("add_wizard", "Show Files"))
        self.label_5.setText(_translate("add_wizard", "Folder:"))
        self.account_folder_change_button.setText(_translate("add_wizard", "..."))
        self.label_7.setText(_translate("add_wizard", "Selective Sync:"))
        self.selective_sync_check.setText(_translate("add_wizard", "Enable"))
        self.last_page.setTitle(_translate("add_wizard", "Success!<br/><br/>The selected account was added. "))

from PyQt5 import QtWebKitWidgets
